ll_project/accounts/urls.py
'''Define o padrão de URLS para contas de usuarios'''

from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    #inclui urls de autenticação default
    path('', include('django.contrib.auth.urls')),
    #pagina de cadastro
    path('register/', views.register, name = 'register'),
]

ll_project/learning_logs/urls.py
#definindo padrões de URL para learning_logs 
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    #pagina inicial
    #o name serve para que o index e etc virem um link lá no base.html e que nos consiga pular de uma pagina para outra só clicando nos links
    path('', views.index, name='index'),
    #paginas para mostrar todos os tópicos 
    path('topics/', views.topics, name= 'topics'),
    #pagina de detalhes para um unico topico
    path('topics/<int:topic_id>/', views.topic, name='topic' ), 
    #pagina para o usuario integarir e criar um novo topico
    path('new_topic/', views.new_topic, name='new_topic'),
    #Pagina para o usuario inserir as entradas dos topicos
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    #é necessario que a url passe o id da pagina por isso
    path('edit_entry/<int:entry_id>/', views.edit_entry, name="edit_entry"), 
]

ll_project/ll_project/urls.py
#importando o painel administrativo
from django.contrib import admin
#path serve para indicar o caminho para a url, uma rota
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # Quando tiver vazio depois da barra quero que ele va para learning_logs.urls
    path('', include('learning_logs.urls')),
]

ll_project/accounts/models.py
from django.db import models

# Create your models here.

ll_project/learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    '''Um tópico que o usuario está apreendendo'''
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)

class Entry(models.Model): 
    #algo especifico apreendido sobre o modulo
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta: 
        verbose_name_plural = 'entries'

    def __str__(self): 
        #retorna a representação da string do modelo
        return f"{self.text[:50]} + ... "
    

ll_project/learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class FormTopic(forms.ModelForm):
    class Meta: 
        model = Topic
        fields = ['text']
        #tiramos o nosso labels
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta: 
        model = Entry
        fields = ['text']
        labels = {'Text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

ll_project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    #cadastra um usuario novo
    if request.method != 'POST':
        #exibe o formulario em branco
        form = UserCreationForm()
    else: 
        #processa o formulario preenchido
        form = UserCreationForm(data = request.POST)
        #verifica se o formulario é valido
        if form.is_valid():
            new_user = form.save()
            #faz o login do usuario e o direciona para a pagina inicial
            login(request, new_user)
            return redirect('learning_logs:index')
    #exibi um formulario branco ou invalido 
    context = {'form': form}
    return render(request, 'registration/register.html', context)

ll_project/learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import FormTopic, EntryForm
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

#request é a requisição do usuario
def index(request): 
    #A pagina inicial para o registro de aprendizagem 
    #render vai pegar o request e renderizar para uma pagina HTML com a caminho que definimos 
    return render(request, 'learning_logs/index.html')

def topics(request):
    #mostra todos os topicos 
    #order_by estou pegando o objeto no banco de dados e ordenados pela data
    topics = Topic.objects.order_by('date_added')
    #criei um dicionario de chave e valor
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    #Mostra um unico topico e todas as suas entradas 
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render (request, 'learning_logs/topic.html', context)

def new_topic(request):
    #adicionar um topico novo
    if request.method != 'POST': 
        #nenhum dado foi enviado; criar um formulario em branco
        form = FormTopic()
    else: 
        #dados do post enviados; processar os dados
        form = FormTopic(data=request.POST)
        if form.is_valid(): 
            form.save()
            return redirect('learning_logs:topics')
    #exibi um formulario em branco ou inválido
    context = {'form':form}    
    return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request, topic_id):
    #adiciona uma nova entrada para o topico especifico
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST': 
        form = EntryForm()
    else: 
        #dados POST enviado, processando os dado 
        form = EntryForm(data=request.POST)
        if form.is_valid():
            #commit salva, faz basicamente um pré salvamento
            new_entry = form.save(commit=False)
            #agora sim peguei os dados do topico
            new_entry.topic = topic
            #agora sim posso salvar
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    
    #exibi um formulario branco ou invalido 
    context = {'topic':topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

def edit_entry(request, entry_id):
    #edita uma entrada existente
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.method != 'POST':
        #REQUISIÇÃO INICIAL; pré-preenche formulario com a entrada atual 
        form = EntryForm(instance=entry)
    else: 
        #dados POST enviados; processar dados
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
        
    context = {'entry': entry, 'topic': topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

#comentatiooos

ll_project/learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}" ><h1>Registro de aprendizagem</h1></a> -
    <a href="{% url 'learning_logs:topics' %}" >Topicos</a>
    {% if user.is_authenticated %}
        Hello, {{user.username}}
    {%else%}
        <a href="{% url 'accounts:register' %}">Registro</a>
        <a href="{% url 'accounts:login' %}">Entrar</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

{% if user.is_authenticated %}
    <hr/>
    <form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <button name="submit">Sair</button>
    </form>
{% endif %}

ll_project/learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

    <p>Edit entry:</p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method ='post' >
        {% csrf_token %}
        {{ form.as_div }}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}

ll_project/learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>Essa aplicação te ajudará a organizar seus estudos.</p>
{% endblock content %}

ll_project/learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

    <p>Add a new Entry:</p>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method ='post' >
        {% csrf_token %}
        {{ form.as_div }}
        <button name="submit">Add Entry</button>
    </form>

{% endblock content %}

ll_project/learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>Add a new topic:</p>

    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="submit">Adicionar</button>
    </form>

{% endblock content %}

ll_project/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>Topico: {{ topic.text }}</p>

    <p>Anotações:</p>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>
    <ul>
        {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p>
                <a href="{% url 'learning_logs:edit_entry' entry.id %} ">Edit entry</a>
            </p>
        </li>
        {% empty %}
        <li>Nenhuma entrada disponível.</li>
        {% endfor %}
    </ul>
{% endblock content %}

ll_project/learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% block content %}

    <p>Topicos</p>
    <ul>
        {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic.text }}</a>
        </li>
        {% empty %}
            <li>Não há topicos adicionados.</li>
        {% endfor %}
    </ul>
        <a href="{% url 'learning_logs:new_topic'%}">Adicionar novo topico</a>

{% endblock content %}